obj = {
  'USD': 'USD - US Dollar',
  'EUR': 'EUR - Euro',
  'GBP': 'GBP - British Pound',
  'NOK': 'NOK - Norwegian Krone',
  'THB': 'THB - Baht',
  'AUD': 'AUD - Australian Dollar',
  'HKD': 'HKD - Hong Kong Dollar',
  'CAD': 'CAD - Canadian Dollar',
  'NZD': 'NZD - New Zealand Dollar',
  'SGD': 'SGD - Singapore Dollar',
  'HUF': 'HUF - Forint',
  'CHF': 'HF - Swiss Franc',
  'UAH': 'UAH - Hryvnia',
  'JPY': 'JPY - Yen',
  'CZK': 'CZK - Czech Koruna',
  'DKK': 'DKK - Danish Krone',
  'ISK': 'ISK - Iceland Krona',
  'SEK': 'SEK - Swedish Krona',
  'HRK': 'HRK - Kuna',
  'RON': 'RON - Romanian Leu',
  'BGN': 'BGN - Bulgarian Lev',
  'TRY': 'TRY - Turkish Lira',
  'ILS': 'ILS - New Israeli Shekel',
  'CLP': 'CLP - Chilean Peso',
  'MXN': 'MXN - Mexican Peso',
  'PHP': 'PHP - Philippine Piso',
  'ZAR': 'ZAR - Rand',
  'BRL': 'BRL - Brazilian Real',
  'MYR': 'MYR - Malaysian Ringgit',
  'RUB': 'RUB - Russian Ruble',
  'IDR': 'IDR - Rupiah',
  'INR': 'INR - Indian Rupee',
  'KRW': 'KRW - Won',
  'CNY': 'CNY - Yuan Renminbi',
  'XDR': 'SDR Int\'l Monetary Fund (I.M.F.)'
}
